source "http://rubygems.org"

gem 'rake', '0.8.7'
gem 'rspec', '2.2.0'
gem 'cucumber', '0.10.6'
gem 'cucumber-rails', "0.4.1"
gem 'nokogiri', "1.5.0"
gem 'capybara', '1.0'
gem 'selenium-webdriver', '0.2.2'

